### ISSUE TITLE
Failed to locate the winutils binary in the hadoop binary path

### ISSUE THREAD

**Issue by yugolf** [negokaz/spark-hands-on-development#2]
http://localhost:9000/ にアクセスした際にバックエンド側のコンソール（backend/run）に下記エラーが出ました。
ブラウザ上にはハッシュタグのランキングと思われるものが正しく（？）表示されています。

```
C:\spark-hands-on-development>activator backend/run
[info] Loading project definition from C:\spark-hands-on-development\project
[info] Set current project to twitter-hashtag-ranking-frontend (in build file:/C:/spark-hands-on-development/)
[info] Running com.example.tagrank.backend.Backend local[4]
[INFO] [10/25/2015 15:13:23.423] [run-main-0] [Remoting] Starting remoting
[INFO] [10/25/2015 15:13:23.749] [run-main-0] [Remoting] Remoting started; listening on addresses :[akka.tcp://backend@127.0.0.1:2552]
[INFO] [10/25/2015 15:13:23.752] [run-main-0] [Remoting] Remoting now listens on addresses: [akka.tcp://backend@127.0.0.1:2552]
[INFO] [10/25/2015 15:13:26.673] [backend-akka.actor.default-dispatcher-4] [akka.tcp://backend@127.0.0.1:2552/user/rankingAnalyzer] === RankingAnalyzer started ===
do
Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
        at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:278)
        at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:300)
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:293)
        at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:76)
        at org.apache.hadoop.mapred.FileInputFormat.setInputPaths(FileInputFormat.java:362)
        at org.apache.spark.SparkContext$$anonfun$hadoopFile$1$$anonfun$32.apply(SparkContext.scala:1016)
        at org.apache.spark.SparkContext$$anonfun$hadoopFile$1$$anonfun$32.apply(SparkContext.scala:1016)
        at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:176)
        at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:176)
        at scala.Option.map(Option.scala:145)
        at org.apache.spark.rdd.HadoopRDD.getJobConf(HadoopRDD.scala:176)
        at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:200)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1919)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:905)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:904)
        at com.example.tagrank.backend.spark.SparkLogic$.analyzeRanking(SparkLogic.scala:52)
        at com.example.tagrank.backend.spark.SparkLogic$$anonfun$1.apply(SparkLogic.scala:19)
        at com.example.tagrank.backend.spark.SparkLogic$$anonfun$1.apply(SparkLogic.scala:19)
        at com.example.tagrank.backend.actor.RankingAnalyzer$$anonfun$receive$1.applyOrElse(RankingAnalyzer.scala:26)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at com.example.tagrank.backend.actor.RankingAnalyzer.aroundReceive(RankingAnalyzer.scala:14)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by negokaz** [comment]
同じような問題がstackoverflowにあがってました。
http://stackoverflow.com/questions/19620642/failed-to-locate-the-winutils-binary-in-the-hadoop-binary-path

[Titus Barik blog](http://www.barik.net/archive/2015/01/19/172716/) から hadoop2.6 を落としてきて解凍したディレクトリを環境変数`%HADOOP_HOME%` に通して、`-Djava.library.path=[HADOOP_HOME]\bin` をシステムプロパティに設定して起動すると解決するみたいです。。。

Sparkのディレクトリ配下にある`bin\spark-shell`を起動して`sc.parallelize(1 to 10).count()`と入力しても同じエラーが出ますか？

**Comment by negokaz** [comment]
Qiitaにも同様の解決法があがってました。
[Apache SparkをTypesafe Activatorから試す #Windowsにはwinutils.exeが必要](http://qiita.com/pyr_revs/items/9bd4a1ef3f40a2f7a804#windows%E3%81%AB%E3%81%AFwinutilsexe%E3%81%8C%E5%BF%85%E8%A6%81)

上記の記事によると、設定するのは`%HADOOP_HOME%`だけで良かったみたいです。
もし試して、解決したら教えて下さい。手順に追記します。

**Comment by yugolf** [comment]
hadoop2.6を落として%HADOOP_HOME% を通せばエラー消えました。

**Comment by negokaz** [comment]
事前準備に追記しました。
インストールの確認は下記の方法でできるでしょうか？

`dir %HADOOP_HOME%\bin\winutils.exe /b`

```
winutils.exe
```

コンソールにファイル名が表示される。存在しない場合はエラーが表示される。

**Comment by yugolf** [comment]
良いと思います。
Hdoopを丸々展開して環境変数に設定したので、このファイルだけで十分かどうかは定かで無いですが。

### 実行結果

```
C:\\spark-hands-on-development>dir %HADOOP_HOME%\bin\winutils.exe /b                                                                                                                     
winutils.exe
```
